# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeCCompiler.cmake.in\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeCXXCompiler.cmake.in\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeCXXInformation.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeClDeps.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeDetermineCXXCompiler.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeDetermineCompiler.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeDetermineCompilerId.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeExpandImportedTargets.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeFindBinUtils.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CheckIncludeFile.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CheckTypeSize.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Compiler/Clang-C.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Compiler/Clang-CXX.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Compiler/Clang.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/CompilerId/Xcode-3.pbxproj.in\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-CXX.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-Clang-C.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-Clang-CXX.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-Clang.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/Applications/CMake\ 2.8-10.app/Contents/share/cmake-2.8/Modules/Platform/UnixPaths.cmake\
/Users/rongji/Work/u2project_deps/ogredeps/CMakeLists.txt\
/Users/rongji/Work/u2project_deps/ogredeps/src/CMakeLists.txt\
/Users/rongji/Work/u2project_deps/ogredeps/src/FreeImage/CMakeLists.txt\
/Users/rongji/Work/u2project_deps/ogredeps/src/freetype/CMakeLists.txt\
/Users/rongji/Work/u2project_deps/ogredeps/src/ois/CMakeLists.txt\
/Users/rongji/Work/u2project_deps/ogredeps/src/zlib/CMakeLists.txt\
/Users/rongji/Work/u2project_deps/ogredeps/src/zziplib/CMakeLists.txt\
/Users/rongji/Work/u2project_deps/ogredeps_mac/CMakeFiles/2.8.10.2/CMakeCCompiler.cmake\
/Users/rongji/Work/u2project_deps/ogredeps_mac/CMakeFiles/2.8.10.2/CMakeCXXCompiler.cmake\
/Users/rongji/Work/u2project_deps/ogredeps_mac/CMakeFiles/2.8.10.2/CMakeSystem.cmake
	/Applications/CMake\ 2.8-10.app/Contents/bin/cmake -H/Users/rongji/Work/u2project_deps/ogredeps -B/Users/rongji/Work/u2project_deps/ogredeps_mac
