# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/rongji/Work/u2project_deps/ogredeps/src/zlib/CMakeLists.txt
	/Applications/CMake\ 2.8-10.app/Contents/bin/cmake -H/Users/rongji/Work/u2project_deps/ogredeps -B/Users/rongji/Work/u2project_deps/ogredeps_ios
